// exam_basics_react/src/App.jsx
import { Routes, Route, Navigate } from 'react-router-dom'
import AppHeader from './components/AppHeader.jsx'
import AppFooter from './components/AppFooter.jsx'
import HomePage  from './pages/HomePage.jsx'
import Page1Page from './pages/Page1Page.jsx'
import Page2Page from './pages/Page2Page.jsx'

export default function App() {
  return (
    <div className="app-container position-relative d-flex flex-column vh-100 overflow-x-hidden overflow-y-auto">
      <AppHeader />
      <main className="position-relative flex-fill">
        <Routes>
          <Route path="/" element={<Navigate to="/home" replace />} />
          <Route path="/home" element={<HomePage />} />
          <Route path="/page1" element={<Page1Page />} />
          <Route path="/page2" element={<Page2Page />} />
        </Routes>
      </main>
      <AppFooter />
    </div>
  )
}

// exam_basics_vue/src/App.vue
<template>
  <div class="app-container position-relative 
              d-flex flex-column vh-100 
              overflow-x-hidden overflow-y-auto">
    <AppHeader />
    <main class="position-relative flex-fill">
      <RouterView />
    </main>
    <AppFooter />
  </div>
</template>

<script setup>
import AppHeader from './components/AppHeader.vue'
import AppFooter from './components/AppFooter.vue'
</script>
