// exam_basics_react/src/components/AppFooter.jsx
export default function AppFooter() {
  console.log('Footer controller...');
  const currentYear = new Date().getFullYear()

  return (
    <div className="container-fluid bg-body-tertiary">
      <p className="fw-lighter fs-xs text-center mb-0 py-2">
        <span>&copy; Copyright&nbsp;&nbsp;2021-{currentYear}</span>
        <span className="ms-2">Keri Informatika, Makó</span>
      </p>
    </div>
  )
}

// exam_basics_vue/src/components/AppFooter.vue
<template>
  <div class="container-fluid bg-body-tertiary">
    <p class="fw-lighter fs-xs text-center mb-0 py-2">
      <span>&copy; Copyright&nbsp;&nbsp;2021-{{ currentYear }}</span>
      <span class="ms-2">Keri Informatika, Makó</span>
    </p>
  </div>
</template>

<script setup>
console.log('Footer controller...');
const currentYear = new Date().getFullYear()
</script>

<style scoped>
.fs-xs {
  font-size: 0.75em;
}
</style>
