// exam_basics_react/src/components/AppHeader.jsx
import './AppHeader.css'
import { NavLink } from 'react-router-dom'

export default function AppHeader() {
  return (
    <nav className="navbar navbar-expand-sm bg-body-tertiary sticky-top">
      <div className="container-fluid">
        <button className="navbar-toggler ms-auto"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>

        <div id="navbarNav" className="collapse navbar-collapse">
          <ul className="navbar-nav mx-auto mt-3 mt-sm-0 text-center">

            {/* Home */}
            <li className="nav-item text-small-caps btn-click-effect rounded">
              <NavLink className="nav-link" to="/home">
                <i className="fa-solid fa-house me-1"></i>
                <span>Kezdőoldal</span>
              </NavLink>
            </li>

            {/* Page1 */}
            <li className="nav-item text-small-caps btn-click-effect rounded">
              <NavLink className="nav-link" to="/page1">
                <i className="fa-solid fa-face-smile-beam me-1"></i>
                <span>Oldal 1</span>
              </NavLink>
            </li>

            {/* Page2 */}
            <li className="nav-item text-small-caps btn-click-effect rounded">
              <NavLink className="nav-link" to="/page2">
                <i className="fa-solid fa-face-grin-tears me-1"></i>
                <span>Oldal 2</span>
              </NavLink>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  )
}

// exam_basics_vue/src/components/AppHeader.vue
<template>
  <nav class="navbar navbar-expand-sm 
              bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <button
        class="navbar-toggler ms-auto"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navbarNav" class="collapse navbar-collapse">
        <ul class="navbar-nav mx-auto mt-3 mt-sm-0 text-center">
          <li class="nav-item text-small-caps btn-click-effect rounded">
            <RouterLink class="nav-link" to="/home">
              <i class="fa-solid fa-house me-1"></i>
              <span>Kezdőoldal</span>
            </RouterLink>
          </li>

          <li class="nav-item text-small-caps btn-click-effect rounded">
            <RouterLink class="nav-link" to="/page1">
              <i class="fa-solid fa-face-smile-beam me-1"></i>
              <span>Oldal 1</span>
            </RouterLink>
          </li>

          <li class="nav-item text-small-caps btn-click-effect rounded">
            <RouterLink class="nav-link" to="/page2">
              <i class="fa-solid fa-face-grin-tears me-1"></i>
              <span>Oldal 2</span>
            </RouterLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<style scoped>
.nav-item:hover {
  background-color: rgba(0, 0, 0, 0.1);
}
.nav-link.router-link-active {
  text-decoration: underline;
  pointer-events: none;
}
.btn-click-effect:not(.disabled):active {
  animation: btnClickEffect 0.4s;
}
@keyframes btnClickEffect {
  0% { transform: none; }
  50% { transform: scale(0.9); }
  100% { transform: none; }
}
</style>
